server:
  port: 8082


spring:
  application:
    name: message-consumer
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mq_consumer
    username: postgres
    password: test123
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: localhost:5672


logging:
  file:
    name: logs/Consumer-log.txt


management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health


info:
  app:
    name: microservice application
    description: consumer service
    version: 1.0.0